language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t yanisble/docker-react:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true yanisble/docker-react npm run test
deploy:
  - provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-1-248952594728"
    bucket_path: "docker-react"
on:
  branch: master
access_key_id: "$AWS-ACCESS-KEY"
secret_access_key: "$AWS-SECRET-KEY"