language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t yanisble/docker-react:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true yanisble/docker-react npm run test